export { default as HomeScreen } from "./HomeScreen/index";
export {default as UploadDocument} from "./Admin/Document/Upload document Page"
export {default as DocumentPage} from "./Admin/Document/Document page/index"
export {default as AdminViewDocument} from "./Admin/Document/View"
export {default as configLocation} from "./Admin/config/Location"
export {default as configDivision} from "./Admin/config/notification"
export {default as configRole} from "./Admin/config/Role"
export {default as Roles} from "./Admin/config/index"
export {default as Pickup} from "./Admin/Pickup"
export {default as Report} from "./Admin/Report"

export {default as AdminViewReport} from  "./Admin/Report/viewReport"
export {default as LocationSearch} from "./Location Champion/Employee Search"
export {default as LocationResult} from "./Location Champion/Search result"
export {default as LocationReport} from "./Location Champion/Report Table"
export {default as LocationView} from "./Location Champion/View"
export {default as EmployeePickLocation} from "./Employee/Pick Location"
export {default as EmployeePickLocationEdit} from "./Employee/Edit Location"